#!/bin/sh

REMOTE="`git remote`"

if [ `echo "$REMOTE" | wc -l` -ne 1 ]; then
	>&2 echo "This command can only be used when there is exactly one remote."
	exit 1
fi

BRANCH="`git symbolic-ref --short HEAD`"

git push -u "$REMOTE" "$BRANCH"
git remote set-branches --add origin "$BRANCH"
