#!/bin/bash

BASE_BRANCH="master"

CHANGES_BRANCH="`git symbolic-ref --short HEAD`"
if [ "$CHANGES_BRANCH" = "$BASE_BRANCH" ]; then
	ANCESTOR="$BASE_BRANCH"
else
	ANCESTOR="`git merge-base "$BASE_BRANCH" "$CHANGES_BRANCH"`"
fi

subl --command close_all
git diff -U0 "$ANCESTOR" | awk -F '[-, ]' '
  /^\+\+\+ b/ { file_name = substr($0, 7) }
  /^@@ -/ && file_name != "" { print file_name ":" $3; file_name = "" }
' | while read FILE_SPEC; do
  subl $FILE_SPEC
done

# # This should work and would be slightly simpler, but while the cursor is at the right place in each file, only the
# # last file gets scrolled to the appropriate place.
# subl $(
#   git diff -U0 "$ANCESTOR" | awk -F '[-, ]' '
#     /^\+\+\+ b/ { file_name = substr($0, 7) }
#     /^@@ -/ && file_name != "" { print file_name ":" $3; file_name = "" }
#   '
# )
