#!/bin/bash

BASE_BRANCH="master"

CHANGES_BRANCH="`git symbolic-ref --short HEAD`"
if [ "$CHANGES_BRANCH" = "$BASE_BRANCH" ]; then
	ANCESTOR="$BASE_BRANCH"
else
	ANCESTOR="`git merge-base "$BASE_BRANCH" "$CHANGES_BRANCH"`"
fi

subl --command close_all
subl `git diff "$ANCESTOR" --name-only` # This first pass is needed so that the second pass scrolls properly
subl $(
  git diff -U0 "$ANCESTOR" | awk -F '[-, ]' '
    /^\+\+\+ b/ { file_name = substr($0, 7) }
    /^@@ -/ && file_name != "" { print file_name ":" $3; file_name = "" }
  '
)
